# ------------------------------------------------------------------------------
# docker-compose.yml
# ------------------------------------------------------------------------------

# Master project docker-compose.yml file, which both defines project specific
# Docker Compose services and overrides those pulled in via "Varilink - Tools"
# submodules in the /tools folder.

version: "3.6"

services:

  wordpress:

    env_file:
      - ./public.env # Public environment variables file (Git tracked).
      - ./secret.env # Secret environment variables file (Git ignored).

    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_AUTO_UPDATE_CORE', false);
        define(
          'FOBV_ENV', getenv( 'FOBV_ENV' )
        );
        define(
          'FOBV_DONATE_CONTEXT', getenv( 'FOBV_DONATE_CONTEXT' )
        );
        define(
          'FOBV_GIFT_AID_CONTEXT', getenv( 'FOBV_GIFT_AID_CONTEXT' )
        );
        define(
          'FOBV_JOIN_US_CONTEXT', getenv( 'FOBV_JOIN_US_CONTEXT' )
        );
        define(
          'FOBV_OPTIONS_CONTEXT', getenv( 'FOBV_OPTIONS_CONTEXT' )
        );
        define(
          'FOBV_SUBSCRIBE_CONTEXT', getenv( 'FOBV_SUBSCRIBE_CONTEXT' )
        );
        define(
          'FOBV_MAILCHIMP_API_KEY', getenv( 'FOBV_MAILCHIMP_API_KEY' )
        );
        define(
          'FOBV_MAILCHIMP_API_ROOT', getenv( 'FOBV_MAILCHIMP_API_ROOT' )
        );
        define(
          'FOBV_MAILCHIMP_LIST_ID', getenv( 'FOBV_MAILCHIMP_LIST_ID' )
        );
        define(
          'FOBV_MAILCHIMP_TEST_LIST_ID', getenv( 'FOBV_MAILCHIMP_TEST_LIST_ID' )
        );
        define(
          'FOBV_MAILCHIMP_MEMBERS_INTEREST_CATEGORY',
          getenv( 'FOBV_MAILCHIMP_MEMBERS_INTEREST_CATEGORY' )
        );
        define(
          'FOBV_MAILCHIMP_VOLUNTEERING_INTEREST_CATEGORY',
          getenv( 'FOBV_VOLUNTEERING_MEMBERS_INTEREST_CATEGORY' )
        );
        define(
          'FOBV_PAYPAL_API_DOMAIN', getenv( 'FOBV_PAYPAL_API_DOMAIN' )
        );
        define(
          'FOBV_PAYPAL_APP_CLIENT_ID', getenv( 'FOBV_PAYPAL_APP_CLIENT_ID' )
        );
        define(
          'FOBV_PAYPAL_APP_SECRET', getenv( 'FOBV_PAYPAL_APP_SECRET' )
        );
        define(
          'FOBV_PAYPAL_BRAND_NAME', getenv( 'FOBV_PAYPAL_BRAND_NAME' )
        );
        define(
          'FOBV_PAYPAL_WEBHOOK_ID', getenv( 'FOBV_PAYPAL_WEBHOOK_ID' )
        );

    volumes:
      # The project's site theme, which is a child of twentytwentythree.
      - &theme "./wordpress/theme/:\
        /var/www/html/wp-content/themes/fobv-site/"
      # The project's site plugin.
      - &site-plugin "./wordpress/plugins/fobv-site/:\
        /var/www/html/wp-content/plugins/fobv-site/:ro"
      # The project's event plugin.
      - &event-plugin "./wordpress/plugins/fobv-event/:\
        /var/www/html/wp-content/plugins/fobv-event/:ro"
      # Plugins from the Varilink WordPress plugins library.
      - &varilink-forms "./wordpress/varilink-plugins/varilink-forms:\
        /var/www/html/wp-content/plugins/varilink-forms:ro"
      - &varilink-log-writer "./wordpress/varilink-plugins/varilink-log-writer:\
        /var/www/html/wp-content/plugins/varilink-log-writer:ro"
      - &varilink-mailchimp "./wordpress/varilink-plugins/varilink-mailchimp:\
        /var/www/html/wp-content/plugins/varilink-mailchimp:ro"
      - &varilink-paypal "./wordpress/varilink-plugins/varilink-paypal:\
        /var/www/html/wp-content/plugins/varilink-paypal:ro"
      # The fontawesome stylesheet and associated webfonts.
      - "./wordpress/theme/node_modules/@fortawesome/fontawesome-free/\
        css/all.min.css\
        :/var/www/html/wp-content/themes/fobv-site/assets/\
        css/fontawesome-free.css"
      - "./wordpress/theme/node_modules/@fortawesome/fontawesome-free/\
        webfonts/\
        :/var/www/html/wp-content/themes/fobv-site/assets/\
        webfonts/"

  wp-cli:

    env_file:
      - ./public.env
      - ./secret.env

    environment:
      - COMPOSE_PROJECT_NAME

    volumes:
      - *theme
      - *site-plugin
      - *event-plugin
      - *varilink-forms
      - *varilink-log-writer
      - *varilink-mailchimp
      - *varilink-paypal
      - "./wordpress/media:\
        /var/www/html/wp-content/uploads/fobv-media:ro"

  gimp:

    volumes:
      - ./wordpress/gimp/:/gimp/
      - ./wordpress/media/:/gimp/dist/
